## Put comments here that give an overall description of what your
## functions do

### makeCacheMatrix ###
## creates a mutable matrix
# matrix --> list of functions
# example call: mutmax <- makeCacheMatrix(INSERTMATRIX)
# you can use mutmax$get to access the INSERTMATRIX
#             mutmax$set to assign a new matrix (replace INSERTMATRIX)
#             mutmax$setinverse will be used by cacheSolve()
#             mutmax$getinverse access to inversed matrix

makeCacheMatrix <- function(x = matrix() ) {
        invM <- NULL
        set  <- function(y) {
                x <<- y
                invM <<- NULL # everytime the matrix is reset, the inverse is deleted
        }
        get <- function() x
        setinverse <- function(inverse) invM <<- inverse # stores externally calculated
                                                         # inverse matrix
                                                         # (from cacheSolve())
        getinverse <- function() invM # access of stored inverse matrix
        
        list(set = set, 
             get = get,
             setinverse = setinverse,
             getinverse = getinverse
        )
}

### cacheSolve ###
## inverses or retrieves inversed mutable matrix
## needs a mutable matrix generated by makeCacheMatrix()
# list of functions --> list of functions
# example call: CacheSolve(mutmax)
 
cacheSolve <- function(x, ...) {
        m <- x$getinverse() # extracts the inversed matrix from x if existent
        if(!is.null(m)) {
                message("getting cached data")
                return(m) # if existent, inversed matrix returned without calculation
        }
        data <- x$get() # retrieve matrix from x
        m <- solve(data, ...) # inverse matrix
        x$setinverse(m) # store inversed matrix in x
        m
}

